
// Auto-generated by AutoPilot on 07-08-2023 at 01:01:07

const express = require('express');
const router = express.Router();

// array of tech topics to blog about
const topics = ['AI', 'Robotics', 'Cloud Computing', 'Cyber Security', 'Blockchain',"TiDB"];

// route to return the array of topics
router.get('/topics', (req, res) => {
    res.json(topics);
});

module.exports = router;

// imported express and router to create a controller
// defined an array of tech topics to blog about
// created a route to return the array of topics when called